name: Go

on:
  push:
    branches: ["**"]

jobs:
  all-in-one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
      - run: go test -json ./...
      - run: test -z $(gofmt -l .); gofmt -l .
      - run: go build ./...
